### ISSUE TITLE
Typo: TANSPORT -> TRANSPORT

### ISSUE THREAD

**Issue by battlesnake** [italrr/nite#1]
https://github.com/italrr/nite/blob/c5544d21cf3737583ac9b203b14ec7bcaa8e7145/src/Engine/Network.hpp#L9

From a quick look, I don't think this constant is used elsewhere in the codebase yet, so it should just be a one-line correction.

**Comment by italrr** [comment]
Sorry for the long time to respond to this issue.

Thank you very much. I corrected the line. Although this constant is not being used anywhere, I believe it could be relevant in the future. nite's Network module is not fully functional yet.

For reference c9703adca5017627b2bc609cbf2e7455f60e97a5
